# Generated by Django 5.1.6 on 2025-02-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('specifications', models.TextField()),
                ('image', models.ImageField(upload_to='mobiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mobile')),
            ],
        ),
    ]
